#### Import packages

In [3]:
#import python packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#### Assigning filename variables

In [1]:
#assigning filename handles to filenames
#assign muscle bath data file to filename variable
#example input: 2019_10_02_Swine_Diaphragm_pretreatment_smof_tudca Formatted_Raw
filename = input("Input filename:" )
#assign variable for excel reference file
#address later with reference file of pretreatment/control baths
ref_filename = ""

Input filename:2019_10_02_Swine_Diaphragm_pretreatment_smof_tudca Formatted_Raw

#### Formatting dataframe

In [12]:
#importing files and processing
#import muscle bath tsv file
df_file = pd.read_csv('./'+filename+".tsv",header=0,sep='\t')
#reformat dataframe
header = df_file.iloc[0]
for i in range(0,9):
    header[i+1] = "Peak"+str(i+1)
df_file = df_file.rename(columns=header)
#drop column with bundle weight & length
df_file.drop(df_file.columns[-1], axis=1,inplace=True)
#df_file = df_file[df_file.columns[:10]]

In [19]:
df_file.head()

,Comments,Peak1,Peak2,Peak3,Peak4,Peak5,Peak6,Peak7,Peak8,Peak9,...,Half max value time,Half max value time,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec
Time,Comments,Peak1,Peak2,Peak3,Peak4,Peak5,Peak6,Peak7,Peak8,Peak9,...,Half max value time,Half max value time,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec,Area Under Curve 9.5sec
12:00:04 PM,NaN,5.213E-2,5.729E-2,6.838E-2,5.138E-2,7.448E-2,4.612E-2,6.751E-2,6.217E-2,4.111E-3,...,2.291E+0,2.339E+0,9.035E-3,-7.296E-2,-3.684E-2,-5.378E-2,1.704E-2,-4.153E-2,1.064E-2,2.470E-2
12:00:14 PM,NaN,6.449E-2,5.909E-2,5.426E-2,5.071E-2,4.307E-2,3.993E-2,5.785E-2,6.052E-2,-3.712E-4,...,3.752E+0,3.802E+0,8.973E-3,-1.951E-2,-4.944E-2,-3.317E-3,-1.667E-2,-2.699E-2,4.138E-3,-4.065E-2
12:00:24 PM,NaN,1.268E+1,7.445E+0,5.585E-1,1.400E+0,1.794E+0,1.551E+0,2.058E+0,3.932E+0,9.757E-1,...,6.900E-2,6.800E-2,-5.936E-1,3.599E+0,1.701E-2,-8.910E-2,8.497E-2,1.929E-1,-2.375E-1,-2.328E-1
12:00:26 PM,NaN,1.268E+1,7.448E+0,5.596E-1,1.398E+0,1.791E+0,1.551E+0,2.054E+0,3.934E+0,9.758E-1,...,6.900E-2,6.800E-2,-9.633E-1,4.185E+0,1.022E-2,-1.584E-1,4.802E-2,2.082E-1,-3.699E-1,-3.414E-1